name: biphip_messenger
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  dio: ^5.3.3
  flutter_dotenv: ^5.1.0
  flutter_spinkit: ^5.2.0
  http: ^1.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.1
  get: ^4.6.5
  flutter_svg: ^2.0.7
  socket_io_client: ^3.0.2
  flutter_webrtc: ^0.12.11
  image_gallery_saver_plus: ^3.0.5
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  flutter_screenutil: ^5.9.3
  
  flutter_localizations:
    sdk: flutter
  internet_connection_checker: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - .env
    - .env.dev
    - .env.example

  fonts:
    - family: BipHip
      fonts:
        - asset: assets/fonts/Icon_font/BipHip.ttf

    - family: BipHip2
      fonts:
        - asset: assets/fonts/Icon_font/BipHip2.ttf

    - family: BipHip3
      fonts:
        - asset: assets/fonts/Icon_font/BipHip3.ttf

    - family: BipHip5
      fonts:
        - asset: assets/fonts/Icon_font/BipHip5.ttf

    - family: BipHip6
      fonts:
        - asset: assets/fonts/Icon_font/BipHip6.ttf

    - family: Chat
      fonts:
        - asset: assets/fonts/Icon_font/Chat.ttf
